### ISSUE TITLE
DataUri downloads do not work on Android 10+

### ISSUE THREAD

**Issue by lucifiel** [duckduckgo/Android#1288]
**Describe the bug**
DataUri download fails with file permission denied error.

Permission android.permission.WRITE_EXTERNAL_STORAGE no longer works in new android versions.
See https://developer.android.com/about/versions/10/privacy/changes and https://developer.android.com/about/versions/11/privacy/storage

**How to Reproduce**
1. Go to https://github.com/Pseudonian/SynergismOfficial/
2. Click on "Settings"
3. Click on "Export the game here"

**Expected behavior**
Download saved to file in Downloads folder.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.88.0, reproduced locally on top of commit 5e2d072f9c9e1a24084ddea4f8a8f94c652f3820
 - Device: Honor Pad V6
 - OS: Android 10
 - Stacktrace from android studio
```
downloadDirectory is /storage/emulated/0/Download
generatedFilename is 6b572ff2-e41b-4073-8343-6ddf8718eae3.txt

2021-06-20 03:22:31.006 2669-2669/com.duckduckgo.mobile.android.debug W/e.android.debug: type=1400 audit(0.0:707021): avc: denied { ioctl } for pid=2669 path="/proc/2669/rtg" dev="proc" ino=2848530 ioctlcmd=0xab20 scontext=u:r:untrusted_app:s0:c232,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c232,c256,c512,c768 tclass=file permissive=0

2021-06-20 03:22:31.539 2669-6052/com.duckduckgo.mobile.android.debug E/DataUriDownloader: Failed to save data uri
    java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at com.duckduckgo.app.browser.downloader.DataUriDownloader.initialiseFilesOnDisk(DataUriDownloader.kt:70)
        at com.duckduckgo.app.browser.downloader.DataUriDownloader.download(DataUriDownloader.kt:45)
        at com.duckduckgo.app.browser.downloader.AndroidFileDownloader.download(FileDownloader.kt:63)
        at com.duckduckgo.app.browser.BrowserTabViewModel$download$1.invokeSuspend(BrowserTabViewModel.kt:1878)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-06-20 03:22:31.539 2669-6052/com.duckduckgo.mobile.android.debug W/BrowserTabViewModel$download: Failed to download file [Failed to download data uri]
```

**Comment by cmonfortep** [comment]
Hi @lucifiel we are aware of the changes introduced in Android 10 but we haven't seen any issue so far with our implementation. Could you check if you have storage permissions enabled for our app? Is the issue only affecting you when downloading data Uri files?

I've tested this using this site (https://dopiaza.org/tools/datauri/examples/index.php) and downloading the image without any issue. 

Thanks.

**Comment by lucifiel** [comment]
Hi @cmonfortep 
Storage permission is enabled in device settings and downloading image from https://dopiaza.org/tools/datauri/examples/index.php gives same error on my device.

I think `android.permission.WRITE_EXTERNAL_STORAGE` is ignored in android 10.
Android Studio inspection info says ```
Scoped storage is enforced on Android 10+ (or Android 11+ if using requestLegacyExternalStorage). In particular, WRITE_EXTERNAL_STORAGE will no longer provide write access to all files; it will provide the equivalent of READ_EXTERNAL_STORAGE instead.
```

Only DataUriDownloader.initialiseFilesOnDisk is affected, downloading images with DownloadManager works fine.

**Comment by lucifiel** [comment]
I was able to reproduce the issue with android virtual device

CPU/ABI: Google APIs Intel Atom (x86)
image.sysdir.1: system-images/android-29/google_apis/x86/
Target: google_apis [Google APIs] (API level 29)

```
E/DataUriDownloader: Failed to save data uri
    java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at com.duckduckgo.app.browser.downloader.DataUriDownloader.initialiseFilesOnDisk(DataUriDownloader.kt:67)
        at com.duckduckgo.app.browser.downloader.DataUriDownloader.download(DataUriDownloader.kt:45)
        at com.duckduckgo.app.browser.downloader.AndroidFileDownloader.download(FileDownloader.kt:63)
        at com.duckduckgo.app.browser.BrowserTabViewModel$download$1.invokeSuspend(BrowserTabViewModel.kt:1878)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
W/BrowserTabViewModel$download: Failed to download file [Failed to download data uri]
I/LoginDetectionJavascriptInterface: LoginDetectionInterface Scanning for forms
I/LoginDetectionJavascriptInterface: LoginDetectionInterface No forms found

```
https://user-images.githubusercontent.com/1196947/122843612-5e893880-d2ef-11eb-8e18-aaa4c508a336.mov

**Comment by lucifiel** [comment]
One possible solution for this issue would be to use `android.provider.MediaStore`.

As it may take some time to implement i propose adding android 10 only workaroud - `android:requestLegacyExternalStorage="true"` line to AndroidManifest.xml.

If that is okay i can make a pull request.
