### ISSUE TITLE
[Bug] Catch decoding exception in DataUriDownloader

### ISSUE THREAD

**Issue by cmonfortep** [duckduckgo/Android#1480]
### Describe the bug

In DataUriDownloader, when we try write the bytes to a file we base64 decode the data. Crashlytics (from ATP) recorded a crash indicating the data couldn't be decoded; we should more gracefully handle this scenario.

### How to Reproduce

Fatal Exception: java.lang.IllegalArgumentException: bad base-64
       at android.util.Base64.decode(Base64.java:163)
       at android.util.Base64.decode(Base64.java:138)
       at android.util.Base64.decode(Base64.java:120)
       at com.duckduckgo.app.browser.downloader.DataUriDownloader.writeBytesToFiles(DataUriDownloader.kt:58)
       at com.duckduckgo.app.browser.downloader.DataUriDownloader.download(DataUriDownloader.kt:47)
       at com.duckduckgo.app.browser.downloader.AndroidFileDownloader.download(FileDownloader.kt:63)

### Expected behavior

A simple try/catch would be enough.

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by salilbc** [comment]
let me take a shot at catching the exception
