### ISSUE TITLE
[Bug] 5.110.2 crash ("A migration from 42 to 41 was required but not found")

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1716]
### Describe the bug

5.110.0 just this morning worked fine, upgrade to 5.110.2 later in the day doesn't run.

7f13598f73eacc1c975006c08d2e02b07e60c73f ? :thinking: 

```
E AndroidRuntime: FATAL EXCEPTION: Thread-10
E AndroidRuntime: Process: com.duckduckgo.mobile.android, PID: 6438
E AndroidRuntime: java.lang.IllegalStateException: A migration from 42 to 41 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)
E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onDowngrade(RoomOpenHelper.java:129)
E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.java:194)
E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.store.HttpsBloomFilterSpecDao_Impl.get(HttpsBloomFilterSpecDao_Impl.java:63)
E AndroidRuntime: 	at com.duckduckgo.httpsupgrade.store.PlayHttpsEmbeddedDataPersister.shouldPersistEmbeddedData(PlayHttpsEmbeddedDataPersister.kt:25)
E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsBloomFilterFactoryImpl.create(HttpsBloomFilterFactory.kt:45)
E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsUpgraderImpl.reloadData(HttpsUpgrader.kt:121)
E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsUpgraderImpl$onApplicationCreated$1.invoke(HttpsUpgrader.kt:74)
E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsUpgraderImpl$onApplicationCreated$1.invoke(HttpsUpgrader.kt:74)
E AndroidRuntime: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

### How to Reproduce

1- Be on 5.110.2 (upgrade from 5.110.0 to 5.110.2 perhaps?)
2- Attempt to run the app

### Expected behavior

The app should run just like it always has.

### Environment

```markdown
- DDG App Version: 5.110.2
- Device: Pixel 4a (5G)
- OS: GrapheneOS
```

**Comment by Ammako** [comment]
It works on a clean install, it's only when upgrading from older version to newer version.

**Comment by cmonfortep** [comment]
Thanks for reporting. Your assumption is correct. In our latest release, we reverted a feature that bumped the database version and that created a db migration bug for those who installed `5.100.0`.

I've removed the apk from those versions to avoid crashes to other users, and we will try to avoid this again in the future. Thanks.
