### ISSUE TITLE
[Help] Error:Configuration with name 'default' not found

### ISSUE THREAD

**Issue by yas9999** [duckduckgo/android#264]
Hello,

i'm new here nice app by the way i really like duckduckgo ♥ 
i'm using android studio 2.2 & in my first import of this project i got this : Error:Configuration with name 'default' not found.
can you please help about solving that problem,

Best regards

**Comment by fgei** [comment]
hi @yas9999, did you check out the onion kit library when cloning the project?

**Comment by yas9999** [comment]
i guess yes ! in project structure + button-->Module dependency :
:libs:OnionKit:libnetcipher
:libs:android-support-v4preferencefragement
:libs:appcompat

**Comment by yas9999** [comment]
@fgei  any help please ?

**Comment by fgei** [comment]
@yas9999 can you try "gradle build --stacktrace" on the terminal and print here the result?

**Comment by yas9999** [comment]
i guess you mean "gradlew build --stacktrace"
this is what i got :
* What went wrong:          
A problem occurred configuring root project 'duckgo'.
> Failed to notify project evaluation listener.
   > Cannot evaluate module libnetcipher : Configuration with name 'default' not found.
   > Could not resolve all dependencies for configuration ':compile'.
      > A problem occurred configuring project ':libs:android-support-v4-preferencefragment'.
         > failed to find target android-22 : C:\Users\lenovo\AppData\Local\Android\Sdk
                            
* Try:                      
Run with --info or --debug option to get more log output.
                            
* Exception is:             
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'duckgo'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.listener.ListenerNotificationException: Failed to notify project evaluation listener.
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:94)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy14.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
        ... 31 more         
Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module libnetcipher : Configuration with name 'default' not found.
        at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.doCall(DependencyManager.groovy:583)
        at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.call(DependencyManager.groovy)
        at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.groovy:577)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.groovy:213)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.groovy:128)
        at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:250)
        at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:500)
        at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:585)
        at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:364)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:231)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:431)
        at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:373)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
        ... 35 more         
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:79)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:192)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:69)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:33)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:69)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.doCall(DependencyManager.groovy:580)
        ... 49 more         
                            
                            
BUILD FAILED

**Comment by fgei** [comment]
ok, then it seems you're missing "android-22" from the sdk folder, can you check you have it or you should download it

**Comment by yas9999** [comment]
i have android 22 i changed it in the project structure & the problem is the same :disappointed: 
& this is my Dependencies : 
![image](https://cloud.githubusercontent.com/assets/5939771/19284285/35688180-8fed-11e6-9697-67f0bf2e7abf.png)

**Comment by fgei** [comment]
there's definitely something wrong in there, we don't have okhttp and picasso should be 2.5.2

can you try to "git submodule update --init" and check if you have a folder named "android-22" in "C:\Users\lenovo\AppData\Local\Android\Sdk"

**Comment by yas9999** [comment]
hello @fgei ,

yes i have folder android-22 also in terminal when i put "git submodule update --init"
i get : 
fatal: Not a git repository (or any of the parent directories): .git
i still don't have any idea from where the problem come from !

**Comment by fgei** [comment]
you get the "not a git repository" error probably because you're not on the right project folder?

can you try to create a new folder, move in the new folder and clone the project with this line on the terminal: "git clone --recursive https://github.com/duckduckgo/android.git"

then you can try to open this with Android Studio and try to build. if it fails please copy here again "gradle build --stacktrace"

**Comment by yas9999** [comment]
wow thank you so much @fgei  👍 
now when i run "gradlew build --stacktrace" i get : BUILD SUCCESSFUL
PS: if i add module dependency in project structure i got the old problem, so i get no need to add them there 😄 

Regards

**Comment by fgei** [comment]
nice, hope it's working now @yas9999 
no need to add or change module dependency in the project structure with gradle!
closing since it's working

**Comment by yas9999** [comment]
yeah thank bro
