### ISSUE TITLE
Changing Package name crashesh application by JNI

### ISSUE THREAD

**Issue by Rautarchit001** [duckduckgo/Android#943]
### How to solve it please help??

`    Process: com.privacy.browser.debug, PID: 4294
    java.lang.UnsatisfiedLinkError: No implementation found for long com.privacy.app.httpsupgrade.BloomFilter.createBloomFilterFromFile(java.lang.String, int) (tried Java_com_allinone_app_httpsupgrade_BloomFilter_createBloomFilterFromFile and Java_com_allinone_app_httpsupgrade_BloomFilter_createBloomFilterFromFile__Ljava_lang_String_2I)
        at com.privacy.browser.app.httpsupgrade.BloomFilter.createBloomFilterFromFile(Native Method)
        at com.app.httpsupgrade.BloomFilter.<init>(BloomFilter.kt:36)
        at com.app.httpsupgrade.api.HttpsBloomFilterFactoryImpl.create(HttpsBloomFilterFactory.kt:53)
        at com.app.httpsupgrade.HttpsUpgraderImpl.reloadData(HttpsUpgrader.kt:132)
        at com.app.global.DuckDuckGoApplication$initializeHttpsUpgrader$1.invoke(DuckDuckGoApplication.kt:254)
        at com.app.global.DuckDuckGoApplication$initializeHttpsUpgrader$1.invoke(DuckDuckGoApplication.kt:71)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)`

**Comment by ashoksinghal** [comment]
@Rautarchit001  looks like the application is using some methods which are defined in the .so file via JNI. And updated package name needs to be updated in the .so files too for accessing the same file. I think you need to create the .so files again with the same package name.

**Comment by cmonfortep** [comment]
@Rautarchit001 exactly, like @ashoksinghal said, bloom filter is the cpp library that we use inside our app. Code is also available inside the cpp folder. If you change the app package, you will need to update also references to that package inside cpp files on that folder (e.g: `https-bloom-lib.cpp`)

**Comment by Rautarchit001** [comment]
Sorry @cmonfortep and @ashoksinghal I don't understand how to do that as I only know java and kotlin language can you please explain what should I do to change the package name folder name

**Comment by ashoksinghal** [comment]
@Rautarchit001, you can refer to this link for same
https://yeephycho.github.io/2016/10/20/How-to-Use-NDK-to-Build-A-Shared-Android_Native-Library/
